env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: 'detect'
plugins:
  - react
  - '@typescript-eslint'
  - 'unused-imports'
rules:
  {
    'comma-dangle': ['error', 'only-multiline'],
    '@typescript-eslint/no-unused-vars': 'off',
    'unused-imports/no-unused-vars':
      [
        'error',
        {
          'vars': 'all',
          'varsIgnorePattern': '^_',
          'args': 'after-used',
          'argsIgnorePattern': '^_',
        },
      ],
  }
