name: Test and deploy

on:
  push:
    branches:
      - master

jobs:
  test_deploy:
    name: test and deploy Y-BuildKite-Monitor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install
        run: |
          yarn install
      - name: build project
        run: |
          yarn build
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: guzhongren
          user_email: guzhongren@live.cn

